### ISSUE TITLE
Error while starting the Node - Failed to connect .. Trying to reconnect again.

### ISSUE THREAD

**Issue by bjajoh** [pieye/nimbus-ros#1]
I adapted the IP Adress and tried to run the driver. But however, it is not working and keeps outputting the following:

Connecting to the Web Socket Please wait:...!
..
..
..
Connecting to the Web Socket Please wait:...!
Connecting to the Web Socket Please wait:...!
Failed to connect .. Trying to reconnect again
Failed to connect .. Trying to reconnect again
Failed to connect .. Trying to reconnect again

**Comment by ipa-vsp** [comment]
Sorry for the delay! You also need change the IP [here](https://github.com/pieye/nimbus-ros/blob/1be6794eaa0438755dafab6a04e571bf4364ee55/nimbus-ros/src/websocket.cpp#L143). Most of the code are not structured yet and I am working on it. Please let me know if you any more issues. I hope this resolve the issue.
